version: '3.8'
services:
  client:
    container_name: $CLIENT_HOSTNAME
    restart: always
    depends_on:
      - api
      - db
    environment:
      - CLIENT_PORT=$CLIENT_PORT
      - CLIENT_HOSTNAME=$CLIENT_HOSTNAME
      - API_PORT=$API_PORT
      - API_HOSTNAME=$API_HOSTNAME

  api:
    container_name: $API_HOSTNAME
    restart: always
    networks:
      - db-api-network
    depends_on:
      - db
    environment:
      - API_PORT=$API_PORT
      - TOKEN_SECRET=$TOKEN_SECRET
      - MONGO_PORT=$MONGO_PORT
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
      - MONGO_DB=$MONGO_DB
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD

  db:
    container_name: ${MONGO_HOSTNAME}
    image: mongo:5.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    networks:
      - db-api-network
    volumes:
      - db_data:/data/db
      - db_config:/data/configdb

networks:
  db-api-network:
    driver: bridge

volumes:
  db_data:
    driver: local
  db_config:
    driver: local
