version: '3.8'
services:
  client:
    image: boysers/angular-dev:1.0
    build:
      context: ./frontend
      dockerfile: ./.docker/dev.dockerfile
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    networks:
      - api-client-network
    volumes:
      - "/app/nod_modules"
      - "./frontend:/app"
    command: /bin/sh -c "npm install && ng serve --host 0.0.0.0 --port $CLIENT_PORT --proxy-config proxy.conf.js --disable-host-check --poll=1000"

  api:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - "./backend:/app"
    ports:
      - "${API_PORT}:${API_PORT}"
    command: /bin/sh -c "npm install && npm run serve"
    networks:
      - api-client-network

  db:
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"

networks:
  api-client-network:
    driver: bridge
