version: '3.8'
services:
  client:
    container_name: angular-frontent
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app

  api:
    container_name: api-nodejs
    ports:
      - "3000:3000"