version: '3.8'
services:
  client:
    container_name: angular-frontent
    build:
      context: ./frontend
      dockerfile: ./.docker/dev.dockerfile
    ports:
      - "${ANGULAR_PORT}:${ANGULAR_PORT}"
    environment:
      - ANGULAR_PORT=$ANGULAR_PORT
      - API_PORT=$API_PORT
      - API_HOSTNAME=$API_HOSTNAME
    volumes:
      - "./frontend:/app"
    command: sh -c "npm install && ng serve --host 0.0.0.0 --port $ANGULAR_PORT --proxy-config proxy.conf.js"

  api:
    container_name: api-express
    build: 
      context: ./backend
      dockerfile: ./.docker/dev.dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - API_PORT=$API_PORT
    volumes:
      - "./backend:/app"
    command: sh -c "npm install && npm run start"