FROM node:16.3-alpine AS builder

WORKDIR /app

COPY . .

RUN npm install && \
  npm run build

FROM node:16.3-alpine

WORKDIR /app

COPY --from=builder /app/dist /app
COPY package.json .

RUN npm install
